ServiceHost = "0.0.0.0"
ServicePort = 8080

[MinIO]
Endpoint = "localhost:9000"
AccessKeyID = "minioadmin"
SecretAccessKey = "minioadmin"
UseSSL = false
BucketName = "particles"

[JWT]
Token = "test"
ExpiresIn = "1h"
SigningMethod = "HS256"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"
